
//Sound effect IDs to be used with PlaySFX and I_PlaySFX
public enum SFX {
    MACHINE_GUN_SHOT,
    SNIPER_RIFLE_SHOT,
    EXPLOSION,
    ENEMY_DEATH,
    ENEMY_HIT,
    BOMB_WHISTLE,
    LEVEL_CLEAR,
    DASH,
    PLAYER_GRUNT,
    KNIGHT_SLASH,
    FLAMETHROWER,
    LMG_SHOT,
    SHOTGUN_SHOT,
    ROCKET_LAUNCHER_SHOT,
    BFG_SHOT,
    MENU_SELECT,
    MENU_CONFIRM,
    MENU_ERROR,
    AMBIENT_0,
    ROUND_CLEAR
}